version: "3.8"

services: 
  bot:
    build: .
    volumes: 
      - .:/bot
    env_file: 
      - .env
  
  mysql:
    image: mysql:5.7
    restart: always
    volumes: 
      - bot_mysql:/var/lib/mysql
    expose: 
      - '3306'
    ports: 
      - '3306:3306'
    env_file: 
      - .env
  
volumes: 
  bot_mysql: